### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by mohamedemrani** [unkn0wn-r1d3r/EvilBurp#1]
Traceback (most recent call last):
  File "C:\Users\WD25\Downloads\Phishlet_Burp_extension.py", line 2, in <module>
    import yaml
ImportError: No module named yaml

	at org.python.core.Py.ImportError(Py.java:327)
	at org.python.core.imp.import_first(imp.java:1232)
	at org.python.core.imp.import_module_level(imp.java:1363)
	at org.python.core.imp.importName(imp.java:1544)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1563)
	at org.python.pycode._pyx4.f$0(C:/Users/WD25/Downloads/Phishlet_Burp_extension.py:4)
	at org.python.pycode._pyx4.call_function(C:/Users/WD25/Downloads/Phishlet_Burp_extension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1742)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zo68.ZD(Unknown Source)
	at burp.Zfr3.ZR(Unknown Source)
	at burp.Zbg2.Zl(Unknown Source)
	at burp.Zxfq.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by unkn0wn-r1d3r** [comment]
pip install pyside6 pyyaml

**Comment by DUptain1993** [comment]
Fixed in the latest `Phishlet_Burp_extension.py`.

**Cause:** `import yaml` fails inside Burp because Jython does not use your system `pip` site-packages. `pip install pyyaml` on the host OS does not make the module available to the extension.

**Fix:** EvilBurp no longer depends on PyYAML — it ships a small built-in YAML writer. Reload the updated extension; no `pip install` is required for YAML.

**Comment by DUptain1993** [comment]
Resolved by the Jython-compatible rewrite: no PyYAML required.
